obj-y				+= clk-mtk.o clk-pll.o clk-gate.o clk-mux.o
obj-$(CONFIG_ARCH_MT6735)	+= clk-mt6735.o clk-mt6735-pll.o clk-mt6735-pg.o
obj-$(CONFIG_ARCH_MT6755)	+= clk-mt6755.o clk-mt6755-pll.o clk-mt6755-pg.o