#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# obj-$(CONFIG_MTK_CAM_CAL_GT24C64A_SUPPORT)			+= gt24c64a.o
obj-y			+= gt24c64a.o