
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_YAS532),y)
obj-y	+=  yamaha532/
endif

ifeq ($(CONFIG_MTK_YAS532_NEW),y)
obj-y	+=  yamaha532-new/
endif

ifeq ($(CONFIG_MTK_ST480),y)
obj-y	+=  st480/
endif