include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/clk/mediatek

obj-y += smi_debug.o
obj-y += smi_common.o

obj-y += mmdvfs_mgr.o

# for WQHD 1.0v only
# ccflags-y += -I$(srctree)/drivers/misc/mediatek/video/