include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(MTK_CUSTOM_PATH)/videox/$(MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/spm/$(MTK_PLATFORM)
obj-y += mt_vcorefs_governor.o
obj-y += mt_vcorefs_manager.o


