
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_BMP180_NEW),y)
obj-y	+=  BMP180-new/
endif

ifeq ($(CONFIG_MTK_BMP280_NEW),y)
obj-y	+=  BMP280-new/
endif
